GET http://localhost:3000/products-api/products

###
POST http://localhost:3000/products-api/products
Content-Type: application/json

{
    "productname":"vivo",
    "price":90000,
    "brand":"rtx"
}


###users

GET http://localhost:3000/user-api/user

###create a user
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "name":"rahul",
    "email":"raju12@gmail.com",
    "password":"hello124",
    "cart":[]
}


### req to add product to cart
PUT http://localhost:3000/user-api/user-cart/userid/698194794f964a93067982c6/productid/69806d3926bb84d01e3b234f/quantity/1